-- QUESTION 1
SELECT round(AVG(UNITPRICE)) AVERAGEPRICE, sum(UNITSINSTOCK) AS TOTALSTOCK, max(UNITSONORDER) AS MAXORDER
FROM PRODUCTS;

-- QUESTION 2
SELECT suppliers.SUPPLIERID, COMPANYNAME, CATEGORYNAME, PRODUCTNAME, UNITPRICE
FROM PRODUCTS
join CATEGORIES
on categories.CategoryID = products.CategoryID
join suppliers
on suppliers.supplierid = products.supplierid;

-- QUESTION 3
SELECT CUSTOMERID, sum(FREIGHT)
FROM ORDERS
GROUP BY CUSTOMERID
HAVING sum(FREIGHT) > "$200";

-- QUESTION 4
SELECT orders.OrderID,contactname, `order details`.UNITPRICE, QUANTITY, DISCOUNT
FROM orders
right join `order details`
on orders.OrderID = `order details`.OrderID
right join customers
on orders.CustomerID = customers.CustomerID;

-- QUESTION 5
SELECT E1.employeeid,
concat(E1.LASTNAME," ",E1.FIRSTNAME) AS EMPLOYEE,
concat(E2.LASTNAME," ", E2.FIRSTNAME) AS MANAGER
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2
ON E1.REPORTSTO = E2.EMPLOYEEID
ORDER BY E1.EMPLOYEEID;

-- QUESTION 6
SELECT avg(UNITPRICE) AS AVERAGEPRICE,
        min(UNITPRICE) AS MINIMUMPRICE,
        max(UNITPRICE) AS MAXIMUMPRICE
        FROM PRODUCTS;
        
-- QUESTION 7
create VIEW CUSTOMERDETAILS AS
(SELECT CUSTOMERS.CUSTOMERID, COMPANYNAME, CONTACTNAME, CONTACTTITLE, ADDRESS, CITY, COUNTRY,PHONE, ORDERDATE, REQUIREDDATE, SHIPPEDDATE
FROM CUSTOMERS
JOIN ORDERS
ON customers.CustomerID = orders.CustomerID);

SELECT *
FROM CUSTOMERDETAILS;
 
-- QUESTION 9
create VIEW PRODUCTDETAILS AS
(SELECT PRODUCTID,COMPANYNAME, PRODUCTNAME, CATEGORYNAME, DESCRIPTION, QUANTITYPERUNIT,UNITPRICE,UNITSINSTOCK, UNITSONORDER,REORDERLEVEL,DISCONTINUED
FROM PRODUCTS
JOIN categories
ON categories.CategoryID = PRODUCTS.CATEGORYID
JOIN suppliers
ON suppliers.SupplierID = products.SupplierID);

SELECT *
FROM PRODUCTDETAILS;

-- QUESTION 10
DROP VIEW CUSTOMERDETAILS;

-- QUESTION 11
SELECT left(CATEGORYNAME, 5) 
FROM CATEGORIES;

SELECT RIGHT(CATEGORYNAME,5) AS SHORTINFO
FROM categories;

-- QUESTION 12
CREATE table SHIPPERS_DUPLICATE2
LIKE SHIPPERS;

INSERT INTO SHIPPERS_DUPLICATE2 (SHIPPERID,COMPANYNAME, PHONE)
SELECT *
FROM SHIPPERS;

SELECT * 
FROM SHIPPERS DUPLICATE;

ALTER TABLE SHIPPERS_DUPLICATE2
ADD EMAIL varchar (255);

-- QUESTION 13
SELECT SHIPPERID,COMPANYNAME,PHONE, concat(LOWER(REPLACE(COMPANYNAME, " ","")), "@GMAIL.COM") AS EMAIL
FROM SHIPPERS;

-- QUESTION 14
SELECT CategoryName, COMPANYNAME,PRODUCTNAME
FROM PRODUCTS
JOIN categories 
ON products.CategoryID = categories.CategoryID
JOIN SUPPLIERS
ON products.SupplierID = suppliers.SupplierID
WHERE CATEGORYNAME = "SEAFOOD";

-- QUESTION 15
SELECT categories.CategoryID, COMPANYNAME, PRODUCTNAME
FROM PRODUCTS
JOIN CATEGORIES
ON products.CategoryID = categories.CategoryID
JOIN suppliers
ON products.SupplierID = suppliers.SupplierID
WHERE categories.CategoryID = 5;

-- QUESTION 16
DROP TABLE SHIPPERS_DUPLICATE;

-- QUESTION 17
SELECT FIRSTNAME, LASTNAME, TITLE, YEAR(now())-year(BIRTHDATE) AS AGE
FROM EMPLOYEES;

-- QUESTION 18
SELECT COMPANYNAME,
 sum(orders.OrderID) AS NoOfOrderssincedecember311994
FROM CUSTOMERS
JOIN ORDERS
ON customers.CustomerID = orders.CustomerID
GROUP BY customers.CustomerID
LIMIT 10;


